version: '3.9'

networks:
  net:
    external: false

services:
  systemo-server:
    container_name: systemo-server
    restart: unless-stopped
    build: ./server/.
    ports:
      - "8700:8700"
    networks:
      - net
  systemo-client:
    container_name: systemo-client
    restart: unless-stopped
    build: ./client/.
    ports:
      - "3000:80"
    networks:
      - net
