version: '3.9'

services:
  systemo-server:
    container_name: systemo-server
    hostname: systemo-server
    restart: unless-stopped
    build: ./server/.
    ports:
      - "8700:8700"
  systemo-client:
    container_name: systemo-client
    hostname: systemo-client
    restart: unless-stopped
    build: ./client/.
    ports:
      - "3000:80"
