version: '3.9'

services:
  systemo-server:
    container_name: systemo-server
    restart: unless-stopped
    build: ./server/.
    expose:
      - 8700
  systemo-client:
    container_name: systemo-client
    restart: unless-stopped
    build: ./client/.
    ports:
      - "8700:80"
