version: '3.9'

services:
  dashboard:
    container_name: dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
    ports:
      - "127.0.0.1:4000:4000"
