version: '3.9'

services:
  dashboard:
    container_name: dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: "Server 01"
      GIN_MODE: release
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_ETC: /hostfs/etc
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_DEV: /hostfs/dev
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /etc:/hostfs/etc:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
      - /dev:/hostfs/dev:ro
    ports:
      - "127.0.0.1:4000:4000"
