version: '3.9'

services:
  systemo:
    container_name: systemo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "./start.sh"
    ports:
      - "3000:80"
