version: '3.9'

services:
  systemo:
    container_name: systemo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROXY_URL=https://sys.tp.unjx.de
    environment:
      - GIN_MODE=release
    ports:
      - "127.0.0.1:4000:4000"
