version: '3.9'

services:
  systemo:
    container_name: systemo
    restart: unless-stopped
    build:
      args:
        - REACT_API_ENDPOINT_URL=https://sys.tp.unjx.de/
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:4000"
